import Footer from "@components/Footer/Footer";
import Navbar from "@components/Navbar/Navbar";
import ReduxProvider from "@redux/ReduxProvider";
import "@styles/globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <Navbar />
          {children}
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
